fix setup scripts

diff --git a/api/Scripts/setup/src/install_tracr_dependencies b/api/Scripts/setup/src/install_tracr_dependencies
--- a/api/Scripts/setup/src/install_tracr_dependencies
+++ b/api/Scripts/setup/src/install_tracr_dependencies
@@ -4,7 +4,6 @@
 REMOTE_HOST=""
 
 MY_DIR=$(dirname "$(realpath "$BASH_SOURCE")")
-PROJECT_ROOT=$("$MY_DIR/project_root")
 
 # Parse command-line options
 while (( "$#" )); do
@@ -24,35 +23,45 @@ while (( "$#" )); do
 done
 
 # Read all package names into an array
-mapfile -t packages < "$PROJECT_ROOT/api/Scripts/setup/src/tracr_dependencies.txt"
+mapfile -t packages < "$MY_DIR/../controller/tracr_dependencies.txt"
+
+# Print brief description of what's happening
+if [ -z "$REMOTE_HOST" ]; then
+    echo "Installing tracr dependencies on local machine..."
+else
+    echo "Installing tracr dependencies on $REMOTE_HOST..."
+fi
 
 for package in "${packages[@]}"
 do
     if [ -z "$REMOTE_HOST" ]; then
         # Local installation
         if dpkg -s $package | grep -q "ok installed"; then
-            echo "$package is already installed."
+            echo "  $package is already installed."
         else
-            echo "Installing $package..."
-            if sudo apt-get install -y $package; then
-                echo "$package installed successfully."
+            echo "  Installing $package..."
+            if sudo apt-get install -y $package > >(sed 's/^/    /'); then
+                echo "  $package installed successfully."
             else
-                echo "Failed to install $package."
+                echo "  Failed to install $package." >&2
+                echo "$(tput setaf 1)Cannot ensure dependencies on local system.$(tput sgr0)" >&2
                 exit 1
             fi
         fi
     else
         # Remote installation
         if ssh "$REMOTE_HOST" "dpkg -s $package" | grep -q "ok installed"; then
-            echo "$package is already installed on $REMOTE_HOST."
+            echo "  $package is already installed on $REMOTE_HOST."
         else
-            echo "Installing $package on $REMOTE_HOST..."
-            if ssh "$REMOTE_HOST" "sudo apt-get install -y $package"; then
-                echo "$package installed successfully on $REMOTE_HOST."
+            echo "  Installing $package on $REMOTE_HOST..."
+            if ssh "$REMOTE_HOST" "sudo apt-get install -y $package" > >(sed 's/^/    /'); then
+                echo "  $package installed successfully on $REMOTE_HOST."
             else
-                echo "Failed to install $package on $REMOTE_HOST."
+                echo "  Failed to install $package on $REMOTE_HOST." >&2
+                echo "$(tput setaf 1)Cannot ensure dependencies on $REMOTE_HOST.$(tput sgr0)" >&2
                 exit 1
             fi
         fi
     fi
 done
+echo "$(tput setaf 2)All dependencies installed successfully.$(tput sgr0)"
