update bash scripts

diff --git a/api/Scripts/setup/src/participant_sys_setup b/api/Scripts/setup/src/participant_sys_setup
--- a/api/Scripts/setup/src/participant_sys_setup
+++ b/api/Scripts/setup/src/participant_sys_setup
@@ -77,7 +77,7 @@ fi
 echo "User 'tracr' can use sudo without password."
 
 # Create a safe tempfile to propogate exit code updates to outer shell
-temp_dir="$HOME/.tracr/tmp"
+temp_dir="/home/tracr/.tracr/tmp"
 sudo mkdir -p "$temp_dir"
 temp_fp="$temp_dir/ecode-setup-participant"
 sudo touch $temp_fp
@@ -102,7 +102,7 @@ else
 echo "\$output"
 echo ""
 fi
-if ! output=\$(sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev git 2>&1); then
+if ! output=\$(sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev git uuid-runtime 2>&1); then
     echo "Failed to install pyenv dependencies: \$output"
     exit_code=\$((\$exit_code | 2))  # Set bit 1
 else
@@ -152,27 +152,31 @@ else
 fi
 echo "Done."
 
-# Add required lines to .bashrc
+# Add required lines to .bashrc if necessary
 echo ""
 echo "--------------------------------------------------------"
 echo "Adding pyenv settings to 'tracr' user's shell configs..."
 echo "--------------------------------------------------------"
 echo ""
-if ! output=\$(echo 'export PYENV_ROOT="\$HOME/.pyenv"' >> ~/.bashrc); then
-    echo "Failed to add PYENV_ROOT to .bashrc: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
-fi
-if ! output=\$(echo 'command -v pyenv >/dev/null || export PATH="\$PYENV_ROOT/bin:\$PATH"' >> ~/.bashrc); then
-    echo "Failed to add pyenv to PATH in .bashrc: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
-fi
-if ! output=\$(echo 'eval "\$(pyenv init -)"' >> ~/.bashrc); then
-    echo "Failed to initialize pyenv in .bashrc: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
-fi
-if ! output=\$(echo 'eval "\$(pyenv virtualenv-init -)"' >> ~/.bashrc); then
-    echo "Failed to initialize pyenv-virtualenv in .bashrc: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
+if ! grep -q 'export PYENV_ROOT=' /home/tracr/.bashrc 2>/dev/null; then
+    if ! output=\$(echo 'export PYENV_ROOT="\$HOME/.pyenv"' >> ~/.bashrc); then
+        echo "Failed to add PYENV_ROOT to .bashrc: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+    if ! output=\$(echo 'command -v pyenv >/dev/null || export PATH="\$PYENV_ROOT/bin:\$PATH"' >> ~/.bashrc); then
+        echo "Failed to add pyenv to PATH in .bashrc: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+    if ! output=\$(echo 'eval "\$(pyenv init -)"' >> ~/.bashrc); then
+        echo "Failed to initialize pyenv in .bashrc: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+    if ! output=\$(echo 'eval "\$(pyenv virtualenv-init -)"' >> ~/.bashrc); then
+        echo "Failed to initialize pyenv-virtualenv in .bashrc: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+else
+    echo "pyenv settings already exist in .bashrc."
 fi
 
 # Check for existence of profile files and select the first one available
@@ -188,22 +192,26 @@ else
     profile=~/.profile
 fi
 
-# Add required lines to selected profile file
-if ! output=\$(echo 'export PYENV_ROOT="\$HOME/.pyenv"' >> \$profile); then
-    echo "Failed to add PYENV_ROOT to \$profile: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
-fi
-if ! output=\$(echo 'command -v pyenv >/dev/null || export PATH="\$PYENV_ROOT/bin:\$PATH"' >> \$profile); then
-    echo "Failed to add pyenv to PATH in \$profile: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
-fi
-if ! output=\$(echo 'eval "\$(pyenv init -)"' >> \$profile); then
-    echo "Failed to initialize pyenv in \$profile: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
-fi
-if ! output=\$(echo 'eval "\$(pyenv virtualenv-init -)"' >> \$profile); then
-    echo "Failed to initialize pyenv-virtualenv in \$profile: \$output"
-    exit_code=\$((\$exit_code | 16))  # Set bit 4
+if ! grep -q 'export PYENV_ROOT=' \$profile 2>/dev/null; then
+    # Add required lines to selected profile file
+    if ! output=\$(echo 'export PYENV_ROOT="\$HOME/.pyenv"' >> \$profile); then
+        echo "Failed to add PYENV_ROOT to \$profile: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+    if ! output=\$(echo 'command -v pyenv >/dev/null || export PATH="\$PYENV_ROOT/bin:\$PATH"' >> \$profile); then
+        echo "Failed to add pyenv to PATH in \$profile: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+    if ! output=\$(echo 'eval "\$(pyenv init -)"' >> \$profile); then
+        echo "Failed to initialize pyenv in \$profile: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+    if ! output=\$(echo 'eval "\$(pyenv virtualenv-init -)"' >> \$profile); then
+        echo "Failed to initialize pyenv-virtualenv in \$profile: \$output"
+        exit_code=\$((\$exit_code | 16))  # Set bit 4
+    fi
+else
+    echo "pyenv settings already exist in \$profile."
 fi
 echo "Done."
 
@@ -213,8 +221,20 @@ echo "----------------------------------------"
 echo "Creating directories for 'tracr' user..."
 echo "----------------------------------------"
 echo ""
-if ! output=\$(mkdir -p ~/.tracr/experiments ~/.tracr/device_info 2>&1); then
+if ! output=\$(sudo mkdir -p /home/tracr/.tracr 2>&1); then
     echo "Failed to create directories: \$output"
+    exit_code=\$((\$exit_code | 32))  # Set bit 5
+fi
+if ! output=\$(sudo mkdir -p /home/tracr/.tracr/experiments /home/tracr/.tracr/device_info 2>&1); then
+    echo "Failed to create directories: \$output"
+    exit_code=\$((\$exit_code | 32))  # Set bit 5
+fi
+if ! output=\$(sudo chmod 777 /home/tracr/.tracr /home/tracr/.tracr/experiments /home/tracr/.tracr/device_info 2>&1); then
+    echo "Failed to ease permissions on .tracr folder: \$output"
+    exit_code=\$((\$exit_code | 32))  # Set bit 5
+fi
+if ! output=\$(sudo chown -R tracr /home/tracr/.tracr 2>&1); then
+    echo "Failed to chown on .tracr folder: \$output"
     exit_code=\$((\$exit_code | 32))  # Set bit 5
 fi
 echo "Done."
@@ -225,10 +245,11 @@ echo "---------------------------------------------"
 echo "Creating my_uuid.txt file for 'tracr' user..."
 echo "---------------------------------------------"
 echo ""
-if ! output=\$(uuidgen > ~/.tracr/my_uuid.txt 2>&1); then
+if ! output=\$(uuidgen > \$HOME/.tracr/device_info/my_uuid.txt 2>&1); then
     echo "Failed to create my_uuid.txt file: \$output"
     exit_code=\$((\$exit_code | 32))  # Set bit 5
 fi
+
 # Workaround to propogate exit code to outer shell
 sudo echo \$exit_code > "$temp_fp"
 
